### ISSUE TITLE
 CCL has caught an exception whilst rendering a block

### ISSUE THREAD

**Issue by Sunekaer** [BloodWorkXGaming/ExNihiloCreatio#141]
CCL Error when having Pyrotheum as heat source and looking at heat sources
```
[14:58:15] [Client thread/ERROR]: 
 CCL has caught an exception whilst rendering a block
  BlockPos:      x:0, y:0, z:0
  Block Class:   class cofh.thermalfoundation.fluid.BlockFluidPyrotheum
  Registry Name: thermalfoundation:fluid_pyrotheum
  Metadata:      0
  State:         thermalfoundation:fluid_pyrotheum[level=0]
 Tile at position
  Tile Class:    null
  Tile Id:       null
  Tile NBT:      null
You can turn off player messages in the CCL config file.

net.minecraft.util.ReportedException: Tesselating block in world
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:95) ~[bvm.class:?]
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:82) [CCBlockRendererDispatcher.class:?]
	at com.elytradev.architecture.client.render.CustomBlockDispatcher.func_175018_a(CustomBlockDispatcher.java:98) [CustomBlockDispatcher.class:?]
	at exnihilocreatio.compatibility.jei.crucible.HeatSourcesRecipe.renderBlock(HeatSourcesRecipe.java:184) [HeatSourcesRecipe.class:?]
	at exnihilocreatio.compatibility.jei.crucible.HeatSourcesRecipe.drawInfo(HeatSourcesRecipe.java:167) [HeatSourcesRecipe.class:?]
	at mezz.jei.gui.recipes.RecipeLayout.drawRecipe(RecipeLayout.java:158) [RecipeLayout.class:?]
	at mezz.jei.gui.recipes.RecipesGui.func_73863_a(RecipesGui.java:222) [RecipesGui.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalArgumentException: Cannot set unlisted property net.minecraftforge.common.property.PropertyFloat@14e1214a to NaN on block thermalfoundation:fluid_pyrotheum, it is not an allowed value
	at pl.asie.foamfix.common.FoamyExtendedBlockState.withProperty(FoamyExtendedBlockState.java:94) ~[foamfix-0.10.3-1.12.2.jar:?]
	at net.minecraftforge.fluids.BlockFluidBase.getExtendedState(BlockFluidBase.java:522) ~[BlockFluidBase.class:?]
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:79) ~[bvm.class:?]
	... 17 more
```

**Comment by SirLyle** [comment]
What versions of each relevant mod do you have? Please share your HeatRegistry.json file in a pastebin.

**Comment by Sunekaer** [comment]
https://pastebin.com/t4BSXnb7 HeatRegistry

Ex Nihilo 1.12-0.3.2
ThermalFoundation-1.12.2-2.6.1.22-universal
jei_1.12.2-4.14.3.246

If you want a complete list of all +200 mods, the pack is FTB Presents Stoneblock 2 version 1.0.0 and newer

**Comment by SirLyle** [comment]
Try specifying the meta data as -1 (wild card) like the default fluid pyrotheum entry does:

    "thermalfoundation:fluid_pyrotheum:-1": 15,

**Comment by SirLyle** [comment]
If my recommendation did not fix the error and it persists on the version 0.3.3.5.1 submit a new issue.
