### ISSUE TITLE
Slimes fail to spawn from Mushrooms in Witch Water.

### ISSUE THREAD

**Issue by Insane96** [BloodWorkXGaming/ExNihiloCreatio#196]
```
[16:33:37] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalAccessError: tried to access method net.minecraft.entity.monster.EntitySlime.func_70799_a(IZ)V from class exnihilocreatio.util.EntityInfo
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.IllegalAccessError: tried to access method net.minecraft.entity.monster.EntitySlime.func_70799_a(IZ)V from class exnihilocreatio.util.EntityInfo
	at exnihilocreatio.util.EntityInfo.spawnEntityNear(EntityInfo.java:41) ~[EntityInfo.class:?]
	at exnihilocreatio.barrel.modes.fluid.BarrelItemHandlerFluid.insertItem(BarrelItemHandlerFluid.java:56) ~[BarrelItemHandlerFluid.class:?]
	at exnihilocreatio.barrel.modes.fluid.BarrelModeFluid.onBlockActivated(BarrelModeFluid.java:87) ~[BarrelModeFluid.class:?]
	at exnihilocreatio.tiles.TileBarrel.onBlockActivated(TileBarrel.java:148) ~[TileBarrel.class:?]
	at exnihilocreatio.blocks.BlockBarrel.func_180639_a(BlockBarrel.java:114) ~[BlockBarrel.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:449) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

```

**Comment by SirLyle** [comment]
What version of forge are you on?

**Comment by Insane96** [comment]
2768

**Comment by Insane96** [comment]
Tried updating to 2824, nothing changed. Still the same error

**Comment by SirLyle** [comment]
Interesting, works when tinkers is installed, but not when it's just ex nihilo ... ok I need to include that function in the access transformer; got tricked by the deobf source in my dev environment saying it was public (due to tinker's access transformer).
